// This file defines three Kubernetes namespaces: ecommerce, monitoring, and logging. Each namespace is labeled with its name and environment (for ecommerce). The namespaces are used to logically separate resources in a Kubernetes cluster.

apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
  labels:
    name: ecommerce
    env: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging